# /$$$$$$$$                                /$$$$$$$           /$$
#|__  $$__/                               | $$__  $$         | $$
#   | $$  /$$$$$$  /$$  /$$  /$$ /$$$$$$$ | $$  \ $$ /$$$$$$ | $$
#   | $$ /$$__  $$| $$ | $$ | $$| $$__  $$| $$$$$$$/|____  $$| $$
#   | $$| $$  \ $$| $$ | $$ | $$| $$  \ $$| $$____/  /$$$$$$$| $$
#   | $$| $$  | $$| $$ | $$ | $$| $$  | $$| $$      /$$__  $$| $$
#   | $$|  $$$$$$/|  $$$$$/$$$$/| $$  | $$| $$     |  $$$$$$$| $$
#   |__/ \______/  \_____/\___/ |__/  |__/|__/      \_______/|__/
#                                                                

mainSettings:
  prefix: "<b><gradient:#F4C4F3:#FC67FA>TownPal</gradient></b>"
  inviteTimeout: 60 # in seconds
  townNameCharacterLimit: 15
  logTownInventory: true # This will create a log file for everything that happens for town inventories
  logTownBank: true # This will create a log file for everything that happens for town banks

bank:
  maxAmount: -1 # use -1 for unlimited amount
  startingAmount: 10 # The amount of money the town will start with

allies:
  enabled: True # This will allow use of the ally commands
  broadcast: True # This will broadcast to chat when a town allies with another town
  maxAllies: 5 # Use -1 for unlimited

enemy:
  enabled: True
  broadcast: True
  maxEnemies: -1 

# Enemy Presence Alerts
enemyAlerts:
  enabled: true # Toggle the enemy presence alerts system
  alertCooldown: 300 # Cooldown between repeated alerts (in seconds)
  alertBroadcast: true # Broadcast the alert to the town members
  message: "&c&lALERT<n>&7Enenmy is in your claim

warSystem:
  enabled: true # Toggle to enable or disable the war system
  automaticWarOnEnemy: true # Automatically declare war when two towns become enemies
  warDuration: 86400 # Default war duration in seconds (24 hours). If you want unlimited, set it to -1
  
upgrades:
  # Healing Fireplace Upgrade
  healingFireplace:
    enabled: true # Toggle the upgrade
    cost: 1000 # The cost of unlocking the upgrade
    healingRadius: 5 # Radius of healing effect around fireplace
    healingAmount: 2 # Amount of regeneration
    particleEffect: true # Toggle particles to show when players are healing
    particle: "HEART" # The particle

  # Town Bank Interest Upgrade
  townBankInterest:
    enabled: true # Toggle the upgrade
    cost: 500 # The cost of unlocking the upgrade
    interestRate: 0.02 # Interest rate (2% per day)
    interestInterval: 86400 # Time interval for interest to be applied (in seconds)

  # Member Upgrade
  memberUpgrade:
    enabled: true # Toggle the upgrade
    cost: 200 # Cost of upgrading
    membersIncrease: 15 # The amount it will be upgraded to

  # Town Warps Upgrade
  townWarps:
    enabled: true # Toggle the upgrade
    cost: 300 # Cost of unlocking warps
    maxWarps: 5 # Maximum number of warps allowed
    warpCooldown: 30 # Cooldown in seconds between warp usages (default 0 means no cooldown)
